# -*- coding: utf-8 -*-
"""file_processor_resilient.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143vVvYJV0RbdL56Yzwl_z7dAcxfFpVQI
"""

import csv
import json
import time
import traceback
from pathlib import Path

def process_csv(file_path):
    total = 0
    rows = 0

    with open(file_path, "r", newline="") as f:
        reader = csv.DictReader(f)

        for row in reader:
            rows += 1
            if "qty" in row and "price" in row:
                total += int(row["qty"]) * float(row["price"])

    return {"rows": rows, "revenue": total}


def main(directory):
    directory = Path(directory)

    files_processed = 0
    files_failed = 0
    error_details = {}

    for file in directory.glob("*.csv"):
        retries = 3

        while retries > 0:
            try:
                result = process_csv(file)
                files_processed += 1
                break

            except PermissionError:
                retries -= 1
                if retries == 0:
                    files_failed += 1
                    error_details[file.name] = "PermissionError after retries"
                else:
                    time.sleep(1)

            except Exception:
                files_failed += 1
                error_details[file.name] = traceback.format_exc()
                break

    report = {
        "files_processed": files_processed,
        "files_failed": files_failed,
        "error_details": error_details
    }

    with open("processing_report.json", "w") as f:
        json.dump(report, f, indent=2)


if __name__ == "__main__":
    folder = input("Enter directory path: ")
    main(folder)